#psql.url=jdbc:postgresql://postgres.railway.internal:5432/railway
#psql.username=postgres
#psql.password=rEeUxUVtcEziXFgfAmQzLvfnJpojsqBd

psql.url=jdbc:postgresql://localhost:5432/easy_planning_poker
psql.username=postgres
psql.password=1q2w#E$R