###############################################
# Production profile: OAuth2 redirect settings #
###############################################

app.frontend-url=https://easysprintpoker.com

app.behind-proxy-enabled=true