spring.config.import = optional:application.secure.properties

spring.application.name=easy_planning_poker

spring.datasource.url=${psql.url}
spring.datasource.username=${psql.username}
spring.datasource.password=${psql.password}

server.port=3344
server.address=0.0.0.0

spring.jpa.hibernate.ddl-auto=update

logging.file.name=logs/easyplanningpoker.log
logging.file.path=logs

logging.level.root=WARN
logging.level.com.baeldung=TRACE
