psql.url=jdbc:postgresql://postgres.railway.internal:5432/railway
psql.username=postgres
psql.password=ehmkHfpLRSzPyVnVIgOCPogsIRvLVOXh

#psql.url=jdbc:postgresql://localhost:5432/easy_planning_poker
#psql.username=postgres
#psql.password=1q2w#E$R

app.jwt.secret=U4vWzv3Qk7TzYwD8mCVq1kNf2sR6xBpZ93yLmA0cHeSkTnPqXrZj5Md8PgRsTuVw
app.jwt.expiration-ms=3600000